#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER test_user WITH LOGIN PASSWORD 'test1234';
	CREATE DATABASE ecommerce;
	GRANT ALL PRIVILEGES ON DATABASE ecommerce TO test_user;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO test_user;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO test_user;

    \c ecommerce
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL