import os

POSTGRES_DB = os.environ.get("POSTGRES_DB")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_DOCKER_HOST = os.environ.get("POSTGRES_DOCKER_HOST")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST")
PORT_HOST = os.environ.get("PORT_HOST")
REDIS_URL = os.environ.get("REDIS_URL")
REDIS_HOST = os.environ.get("REDIS_HOST")


class Config:
    SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{PORT_HOST}/{POSTGRES_DB}"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    CACHE_REDIS_URL = REDIS_URL
    CACHE_TYPE = 'redis'