"""initial migration

Revision ID: c74a5daa4746
Revises: 
Create Date: 2025-02-09 11:48:02.088016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74a5daa4746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecommerce', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_constraint('unique_order', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecommerce', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_order', ['order_id'])
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
